### ISSUE TITLE
Pq usar sequalize en vez de prisma ? 🤔

### ISSUE THREAD

**Issue by victoMR** [LuisGOSI/GreenWaste_Pagina#1]
![BatmanThinkingGIF](https://github.com/LuisGOSI/GreenWaste_Pagina/assets/77412296/1cb17ccf-3262-4b2d-9e4d-553f8728e277)
@LuisGOSI

**Comment by LuisGOSI** [comment]
Ta mas facil pa

**Comment by victoMR** [comment]
nom
